package testapp_test

import (
	"net/http"
	"testing"

	"github.com/voxpupuli/enterprise-console/internal/runtime"
	"github.com/voxpupuli/enterprise-console/internal/testapp"
)

// 4.1: one instance starts against generated credentials and answers
// /health.
func TestSingleInstanceServesHealth(t *testing.T) {
	c := testapp.NewCluster(t)
	inst := c.Start(testapp.Config{Mode: runtime.ModeAll})

	if got := inst.StatusOf(t, "/health"); got != http.StatusOK && got != http.StatusServiceUnavailable {
		// Either is acceptable: these instances point at no openvoxdb, so
		// a dependency can legitimately report unhealthy. What matters is
		// that the endpoint is served at all.
		t.Errorf("GET /health = %d, want 200 or 503", got)
	}
}

// 4.2: no fixture from certs/ is involved - the instance above started
// from material generated per-cluster. Asserted by starting an instance
// with the repo's working directory unchanged and no CONSOLE_*_FILE
// pointing into certs/.
func TestInstanceUsesGeneratedCredentials(t *testing.T) {
	c := testapp.NewCluster(t)
	inst := c.Start(testapp.Config{Mode: runtime.ModeAll})

	// The version endpoint is unauthenticated and always served, so a
	// 200 here proves the instance completed startup - which it could
	// only do having loaded a signing key and openvoxdb client
	// certificate, both generated by the harness.
	if got := inst.StatusOf(t, "/api/v1/version"); got != http.StatusOK {
		t.Errorf("GET /api/v1/version = %d, want 200", got)
	}
}

// 4.3: two instances run concurrently against one shared schema, each on
// its own port.
func TestTwoInstancesRunConcurrently(t *testing.T) {
	c := testapp.NewCluster(t)
	a := c.Start(testapp.Config{Mode: runtime.ModeAll})
	b := c.Start(testapp.Config{Mode: runtime.ModeAll})

	if a.BaseURL == b.BaseURL {
		t.Fatalf("both instances bound the same address %s", a.BaseURL)
	}
	for _, inst := range []*testapp.Instance{a, b} {
		if got := inst.StatusOf(t, "/api/v1/version"); got != http.StatusOK {
			t.Errorf("%s: GET /api/v1/version = %d, want 200", inst.BaseURL, got)
		}
	}
}

// 4.4: stopping one instance leaves the other serving. This is the
// property every later failover assertion rests on.
func TestStoppingOneInstanceLeavesTheOtherServing(t *testing.T) {
	c := testapp.NewCluster(t)
	a := c.Start(testapp.Config{Mode: runtime.ModeAll})
	b := c.Start(testapp.Config{Mode: runtime.ModeAll})

	a.Stop(t)

	if got := b.StatusOf(t, "/api/v1/version"); got != http.StatusOK {
		t.Errorf("survivor: GET /api/v1/version = %d, want 200", got)
	}
}

// Different modes start from the same harness, which is what the
// per-mode surface tests need.
func TestEveryModeStarts(t *testing.T) {
	c := testapp.NewCluster(t)
	for _, mode := range runtime.Modes() {
		t.Run(string(mode), func(t *testing.T) {
			inst := c.Start(testapp.Config{Mode: mode})
			if got := inst.StatusOf(t, "/health"); got == 0 {
				t.Errorf("mode %q served no response on /health", mode)
			}
		})
	}
}
